### ISSUE TITLE
Support for combination of @Context and HttpHeaders

### ISSUE THREAD

**Issue by Tibor17** [micronaut-projects/micronaut-jaxrs#175]
### Expected Behavior

@Context HttpHeaders headers; // field in a class

@GET
doGet(@Context HttpHeaders headers) // resource method

### Actual Behaviour

@GET
doGet(HttpHeaders headers)
//This works only.

### Environment Information

Ubuntu 20
JDK 17

### Version

3.2.0

**Comment by Tibor17** [comment]
Additionally, I retrieved empty string instead of null for header which does not exist in the HTTP request.
See the method `getHeaderString()`.

**Comment by sdelamo** [comment]
> @context HttpHeaders headers; // field in a class

I think that it is expected behaviour because JAX-RS Resources in Micronaut are `@Singleton`. They are not `@RequestScope`.
