### ISSUE TITLE
javax AsynResponse equivalent support in Micronaut 

### ISSUE THREAD

**Issue by subash89** [micronaut-projects/micronaut-jaxrs#268]
### Issue description

In the resource method, in jaxrs  it's possible to use `@Suspended final AsyncResponse asyncResponse` where users can invoke multiple backends in async manner, do transformation on it inside the Future/Observable subscriber callback and eventually invoke `asyncResponse.resume(myFinalResponseObject)`.

Is there any equivalent support for this in micronaut to achieve this ?

**Comment by graemerocher** [comment]
the equivalent is to use a reactive return type like `Mono` or `Flux` from reactor

**Comment by subash89** [comment]
Thanks!

**Comment by subash89** [comment]
@graemerocher  I tried even with micronaut-rxjava2 module, like we can return Observable<T> also. That's great.
Quick question:  But looks like  it does not work with micronaut-rxjava1. Complaining about trying to find a serializer for the rxjava. So is micronaut-rxjava1 is not supported for Asyn responses ?

**Comment by graemerocher** [comment]
you need the `micronaut-rxjava1` module on your classpath
