### ISSUE TITLE
JaxRsUriBuilder.uri does not include query

### ISSUE THREAD

**Issue by mpkorstanje** [micronaut-projects/micronaut-jaxrs#450]
### Expected Behavior

Parsing a link header `<https://example.com?page=0>; rel="next"` using `jakarta.ws.rs.core.Link.valueOf` should result in a `Link` object that includes the query `page=0` part of the uri.

### Actual Behaviour

The query part is omitted because eventually `JaxRsUriBuilder.uri` is invoked which does not copy the query.

https://github.com/micronaut-projects/micronaut-jaxrs/blob/d84e887276f96a45324cc8fc3ca927c62d61fb90/jaxrs-server/src/main/java/io/micronaut/jaxrs/runtime/core/JaxRsUriBuilder.java#L59-L69

### Steps To Reproduce

```java
import jakarta.ws.rs.core.Link;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class LinkTest {
  @Test
  void test(){
    Link link = Link.valueOf("<https://example.com?page=0>; rel=\"next\"");
    assertEquals("https://example.com?page=0", link.getUri().toString());
  }

}
```

### Environment Information

- JDK: Temurin 17.0.5
- micronaut-jaxrs-server:4.5.0

### Version

4.5.0

**Comment by dstepanov** [comment]
Fixed in the latest versio
