### ISSUE TITLE
No bean definition classes created with Micronaut 2 for JaxRS

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-jaxrs#69]
A few tests fail during the Micronaut 2 upgrade. See PR #9 and https://github.com/micronaut-projects/micronaut-jaxrs/pull/9/checks?check_run_id=1165063150#step:7:225

I've debugged and comparing the execution of Micronaut 1.3 and Micronaut 2 and I've found a few differences.

### Classes generated at compile time

This is the final cause of the tests failures. With Micronaut 1 seven different classes are generated at compile time. For Micronaut 2, only two classes are created. That's why the test fails with `java.lang.ClassNotFoundException: test.$TestDefinition`

**Micronaut 1**

![image](https://user-images.githubusercontent.com/559192/94277458-e2251d00-ff49-11ea-8332-a0ff648f4586.png)

**Micronaut 2**

![image](https://user-images.githubusercontent.com/559192/94277604-14cf1580-ff4a-11ea-8e58-e7dc647244a0.png)

### Execution of the visitor

This comment about Micronaut Data in core https://github.com/micronaut-projects/micronaut-core/blob/466624c8777fefc0ea2399e5a163caeed87299f2/inject-java/src/main/java/io/micronaut/annotation/processing/TypeElementVisitorProcessor.java#L88 made me define in `JaxRsTypeElementVisitor`:

```java
public VisitorKind getVisitorKind() {
    return VisitorKind.ISOLATING;
}
```

But it doesn't make any difference. I see that the visitor is executed, but the bean definition classes are not created.

### Loaded visitors

The visitors are in the same order, the only difference is that in Micronaut 2 there is a new one: `ExecutableVisitor`

**Micronaut 1**

![image](https://user-images.githubusercontent.com/559192/94278274-e998f600-ff4a-11ea-815e-0bba028236c8.png)

**Micronaut 2**

![image](https://user-images.githubusercontent.com/559192/94278231-de45ca80-ff4a-11ea-8f3f-b2c34c71d432.png)

### More info

Other tests fail like: 
- https://github.com/micronaut-projects/micronaut-jaxrs/pull/9/checks?check_run_id=1165063150#step:7:344
- https://github.com/micronaut-projects/micronaut-jaxrs/pull/9/checks?check_run_id=1165063150#step:7:496
- https://github.com/micronaut-projects/micronaut-jaxrs/pull/9/checks?check_run_id=1165063150#step:7:605

And a few more, but I think the root cause is that the bean definition classes are not being generated correctly.

After trying to debug the visitors code and how everything is generated I wasn't able to find anything else. This issue may be something introduced in core but I don't know what changes were done.

@graemerocher any thoughts or comments about how to fix this?

**Comment by asodja** [comment]
@ilopmar `java.lang.ClassNotFoundException: test.$TestDefinition` can be fixed, if you add @Path to class `Test`. E.g. in HttpMethodAnnotationSpec."test mapped annotation from interface":
```
@javax.ws.rs.Path("/")
class Test implements TestService {
```

**Comment by ilopmar** [comment]
@asodja I'm wondering if that's the correct way to fix this, because the test was passing in Micronaut 1.x without that annotation.

**Comment by graemerocher** [comment]
I think this is linked to the changes around a class requiring a bean defining annotation. @jameskleeh ?
