### ISSUE TITLE
Controller path not found in simple starter (Micronaut v2.2.2) 

### ISSUE THREAD

**Issue by buckfeng** [micronaut-projects/micronaut-jaxrs#87]
### Description

A controller in a starter project using Micronaut v2.2.2 was mapping the path incorrectly.

### Steps to Reproduce

1. Create a starter from https://micronaut.io/launch
2. select version 2.2.2, java 8, maven, jax-rs, logback
3. import the project into Intellij IDEA
4. enable annotation processing
5. add a controller

```java
@Controller("/v1")
public class PingController {`
	@Get("/ping")
	@Produces(MediaType.TEXT_PLAIN)
	public String ping() {
		return "Pong " + Instant.now();
	}
}
```

### Expected Behaviour

I'd expect that calling `GET localhost:8080/v1/ping` should return `Pong 2020-12-24T02:40:17.836932200Z`. 

### Actual Behaviour

However, `GET localhost:8080/v1/ping` was returning `{"message":"Page Not Found","_links":{"self":{"href":"/v1/ping","templated":false}}}`

Strangely, calling `GET localhost:8080/v1` returned `Pong 2020-12-24T02:40:17.836932200Z`.

### Environment Information

- **Operating System**: windows
- **Micronaut Version:** 2.2.2
- **JDK Version:** 11

The following was observed from the log at startup:

`20:11:25.106 [main] WARN  io.micronaut.core.reflect.ClassUtils - Request argument binder [io.micronaut.jaxrs.runtime.ext.bind.CookieRequestArgumentBinder@11acdc30] triggered the use of reflection for types []`

`20:11:25.988 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 1897ms. Server Running: http://localhost:8080`

**Comment by sdelamo** [comment]
@buckfeng Could you help me understand the use case? why do you want to use jaxrs but use Micronaut's `@Controller` annotation instead?

**Comment by wetted** [comment]
> @buckfeng Could you help me understand the use case? why do you want to use jaxrs but use Micronaut's `@Controller` annotation instead?

I think a legitimate use case if you want to migrate a legacy jax-rs application to Micronaut, an endpoint at a time. The module [docs Introduction](https://micronaut-projects.github.io/micronaut-jaxrs/latest/guide/index.html#introduction) mentions it as a motivation.

**Comment by wetted** [comment]
This is an example I used to validate the issue: https://github.com/wetted/Issue87MNJaxRS.git
